# Generated by Django 3.1.3 on 2021-01-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_prodbrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
    ]
