# Generated by Django 3.1.3 on 2021-01-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
